### ISSUE TITLE
How to config it to run

### ISSUE THREAD

**Issue by WhatsVPN** [comp500/SSLSocks#1]
Hello buddy,
Could you list some example config ?

**Comment by comp500** [comment]
Hi,
I've added a [basic explanation](https://github.com/comp500/SSLSocks/blob/master/README.md) of how to use the app and what it requires to build it.
I've also made [a release](https://github.com/comp500/SSLSocks/releases/tag/v0.0.1-beta) so you can install the APK without having to build it yourself.
