### ISSUE TITLE
help me Constants

### ISSUE THREAD

**Issue by phreakingus** [comp500/SSLSocks#10]
public static final String DEF_CONFIG =
            "foreground = yes\n" +
                    "client = yes\n" +
					"pid = \n" +
                    "[shadowsock]\n" +
		        	"accept= 2323\n" +
		        	"connect= 127.0.0.1:8443\n" +
		        	"sni= example.com";

**Comment by comp500** [comment]
Are you working with @nixwizard with this, to add configuration to the APK? If so, don't make another issue for the same issue. I will add a proper system to preload the APK with configurations soon, from the discussions in #9. If you are not going to use this system for the specific purpose of MDM provisioning, I am unlikely to support it, as I am planning to add my own systems for sharing existing configurations with lower friction than exists now. (e.g. links, QR codes, etc.)

It is also unclear what you want me to help you with, however I do know that the DEF_CONFIG constant cannot be used in this way, as the pid file used for stunnel is appended to this constant to create the inital configuration - the pid file location may change so it must be determined at runtime.
