### ISSUE TITLE
integration with OpenVPN

### ISSUE THREAD

**Issue by fa1rid** [comp500/SSLSocks#11]
Hi,
Do you know if you can integrate this app to make it work as a tunnel for OpenVPN (https://github.com/schwabe/ics-openvpn)?
To make them work as one app with one click.
Currently I am using them together to connect OpenVPN server as I have some networks where OpenVPN is blocked by deep packet inspection and the only tool works is Stunnel. 

This OpenVPN client has the the ability to exclude apps from it's routing system so when you connect the VPN, the Stunnel stays with direct connection that doesn't go through the VPN.

Are you able to combine SSLSocks(Stunnel) and the OpenVPN functionality in that client together in one App so when you press one button it will automatically activate Stunnel, then OpenVPN connects through it?

Regards.

**Comment by comp500** [comment]
I don't want to integrate OpenVPN functionality directly into SSLSocks, as that would significantly increase the size and complexity of SSLSocks. There does seem to be [an API](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/api/RemoteAction.java) in ics-openvpn, so I should be able to add integration with that.

I don't have much time at the moment to do this, but I might have a bit of free time next week so I'll look into adding this functionality then.

**Comment by fa1rid** [comment]
Alright thanks. Is there any possible way we can communicate directly? I might have some work opportunity with you. Thanks
________________________________

**Comment by comp500** [comment]
I prefer [Keybase](https://keybase.io/comp500) if possible, or you can DM me on Reddit, or email me at my username at infra.link.

**Comment by phreakingus** [comment]
integrates openvpn or ssh, please

**Comment by comp500** [comment]
Integration has been added in 2e7dd79
