### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by shirtjs** [comp500/SSLSocks#13]
Hi there,

I'm wondering if you have any plans to release SSLSocks on the Play Store. If funding is an issue, I'd be happy to let you use my Google Play License to put it on the Play Store.

Thanks for the awesome app!

**Comment by comp500** [comment]
Thanks for helping me with this!

**Comment by mrbluecoat** [comment]
@shirtjs and @comp500 thanks so much for deploying to the Play Store -- worked great on Android 9!
