### ISSUE TITLE
Can't open pem/pfx files which are password protected

### ISSUE THREAD

**Issue by scott1981** [comp500/SSLSocks#16]
Hi,

I love this app, it is by far better than what i was using before in Android and love the ability to edit stunnel.conf from the UI.

However you can't open passphrase protected pfx or pem files. It is much safer to store them encrypted than in plain text on the phone.

Thanks.

**Comment by comp500** [comment]
I'm not sure if you can pass the keys to stunnel in a secure way, as stunnel (the way it is set up currently) has to use Android's filesystem to read the keys anyway.

I guess I could make SSLSocks decrypt the key and store it in plaintext while the stunnel process is running, but that means anything that would be able to obtain the key from the Android filesystem would also be able to obtain it while SSLSocks is running.
