### ISSUE TITLE
PKCS12: Error "Header too long"

### ISSUE THREAD

**Issue by RichardBeisser** [comp500/SSLSocks#17]
Hello,

i installed SSLSocks App from Google Playstore.
Now I get an error after loading the p12-File.
The Log is saying: d2i_PKCS12_BIO: crypto/asn1/asn1_lib.c:101:error:0D07207B:asn1 encoding routines:ASN1_get_object: header too long

Is there anything i can do?

My config:
```
foreground = yes
pid = /data/user/0/link.infra.sslsocks/files/pid
sslVersionMin = TLSv1.2
checkHost = xxxxx.myftp.org
verifyChain = yes
CAfile= fullchain1.pem

cert = android1.p12
key = android1.pem

sslVersionMin = TLSv1.2

[openvpn]
client = yes
accept = 0.0.0.0:55554
connect = xxxxx.myftp.org:443
```

**Comment by comp500** [comment]
You'll need to convert the .p12 certificate to a .pem file, for example using OpenSSL: `openssl pkcs12 -in file.p12 -out file.pem`

**Comment by RichardBeisser** [comment]
??
But your App is saying for every file-import that file has to be .pem oder .p12.
So i supposed that private key have to be in pem-Format, and Cert has to be in .p12
Do both have to be in .pem?

**Comment by comp500** [comment]
Ah right, I think newer versions of stunnel did add support for .p12. The error suggests that your .p12 file is corrupt or incorrect though, converting it to .pem may help. Also, if your .p12 file is encrypted with a password, it won't work with stunnel, so you'll need to remove the password.

**Comment by RichardBeisser** [comment]
Thanks for fast replay.
the message is not comming  from your app SSLSocks? Is it comming from stunnel?

By the way, I am using this tutorial:
https://hamy.io/post/0011/how-to-run-stunnel-on-your-android-device/

Do I really need to download stunnel, or ist stunnel already integrated in your app?
If stunnel executable is necessary, is there a certain place where the file have to be placed in so that your app use the file?

**Comment by comp500** [comment]
The message is coming from stunnel, yes. It's already integrated in the app, you don't need to download it.

See https://www.stunnel.org/static/stunnel.html for the full stunnel manual and https://www.stunnel.org/lists.html for the stunnel community support mailing list.
