### ISSUE TITLE
Question: Using android-integrated CA-Certs possible?

### ISSUE THREAD

**Issue by RichardBeisser** [comp500/SSLSocks#18]
Hello,

I am using a Cert from Let's Encrypt on my stunnel Server.
On my Clients (here my Android devices), I want to use the Parameter CApath.
Is it possible the CA-Certs of android for SSLSocks?
Because Let's Encrypt is a official CA-Authority (certified itself by DST Root CA X3), all Certs from Let's Encrypt should be verified automatically.
What is the correct path for these Certs so that I get a complete CA-Hierachie?

Thanks.

**Comment by comp500** [comment]
I don't think stunnel supports using the system's CA certificates to verify certificates, so you have to supply the certificate yourself with the `CAfile` option (as well as `verifyPeer`). It may be easier to use a self-signed certificate, but if you want to use Let's Encrypt certificates you can use the root certificates at https://letsencrypt.org/certificates/ - you'll want to use the `checkHost` and `verifyChain` options to ensure that stunnel doesn't just accept *any* Let's Encrypt certificate regardless of the hosts it's valid for.

**Comment by RichardBeisser** [comment]
you are right. My Server is using a let's encrypt-cert and keys, and for my clients, i am using a private self-signed pki. I am using both, verifyChain on the Clients including checkhost to verify the server, and verifyPeer on the server to check the clients.

I made some google-search.
It is not possible to access the Certs and keys in Android via the filesystem. But there is an api to do this:
https://developer.android.com/training/articles/keystore

Is this which have to be done by your SSLSocks-App or stunnel which you integrated in your app?

**Comment by comp500** [comment]
I don't think the Android keystore will be appropriate for this - it doesn't give you access to the CA certificates, it's for generating your own private key and doing encryption with it. It intentionally doesn't allow extracting the key after generating it, so it wouldn't be usable by SSLSocks, and I don't know if it even supports the encryption algorithms necessary for TLS.
