### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by noman720** [comp500/SSLSocks#3]
Hi @comp500 
I am trying to configure in Android Nougat, but I found this error! Can you please explain why I am getting this error?

LOG5[ui]: stunnel 5.49 on arm-unknown-linux-androideabi platform
LOG5[ui]: Compiled/running with OpenSSL 1.1.0i  14 Aug 2018
LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI
LOG5[ui]: Reading configuration from file /data/data/link.infra.sslsocks/files/config.conf
LOG5[ui]: UTF-8 byte order mark not detected
LOG5[ui]: FIPS mode disabled
LOG4[ui]: Service [squid] needs authentication to prevent MITM attacks
LOG5[ui]: Configuration successful
LOG5[ui]: Binding service [squid] to 127.0.0.1:8080: Address already in use (98)

**Comment by comp500** [comment]
This error means that some other program has opened port 8080 before stunnel could (already in use).

Try force closing the app, it should close any other instances of stunnel. Do you have any other services running on your phone that listen on port 8080? If you can't find which app it is, you could also try restarting your phone.

**Comment by comp500** [comment]
Closing due to age.

**Comment by FxMath123** [comment]
I got this error too.
Binding service [ssh] to 0.0.0.0:10000: Address already in use (98)
I tried 127.0.0.1: 10000, try with squid, try to Force Close App and start again.
But always shows this error.
