### ISSUE TITLE
ANDROID_DATA not set!

### ISSUE THREAD

**Issue by FxMath123** [comp500/SSLSocks#5]
First lines of Log shows:
__bionic_open_tzdata_path: ANDROID_DATA not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!

But Configuration successful

Any idea how to fix it?
Im using SSH.

**Comment by comp500** [comment]
I don't think this was created by either SSLSocks or stunnel, it's something to do with the execution of stunnel in the shell.

A google search came up with https://android.stackexchange.com/a/171474, could you see if that fixes the issue?

**Comment by FxMath123** [comment]
Thanks.
