### ISSUE TITLE
LOG5[ui]: Binding service [ssh] to 0.0.0.0:10000: Address already in use (98)

### ISSUE THREAD

**Issue by FxMath123** [comp500/SSLSocks#6]
I got this error.
Binding service [ssh] to 0.0.0.0:10000: Address already in use (98)
I tried 127.0.0.1: 10000, try with squid, try to Force Close App and start again. Restart device.
But always shows this error.

**Comment by comp500** [comment]
You could try changing the port to something else, like 10001. Just change `accept = 10000` to `accept = 10001` in the config.

**Comment by FxMath123** [comment]
Thanks.
I tried different ports, 10001,1002,... or 8000,.... but same error.

**Comment by comp500** [comment]
What is the output of `netstat -at` in a terminal emulator (like [this one](https://play.google.com/store/apps/details?id=jackpal.androidterm)) when SSLSocks isn't running? If you are rooted, run the command with sudo.

**Comment by FxMath123** [comment]
SSLSocks is off.  Results are:
hero2lte:/ $ netstat -at
Active Internet connections (established and servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 Samsung-Galaxy-S7:60995 ec2-52-58-22-25.eu:5223 TIME_WAIT
tcp        0      0 Samsung-Galaxy-S7:33452 ec2-35-176-97-12.e:5228 TIME_WAIT
tcp6       0      0 ::ffff:192.168.1.:57969 ::ffff:172.217.22:https ESTABLISHED
tcp6       0      0 ::ffff:192.168.1.:56594 ::ffff:74.125.71.1:5228 ESTABLISHED
tcp6       0      0 ::ffff:192.168.1.:57970 ::ffff:172.217.22:https ESTABLISHED
tcp6       0      1 ::ffff:192.168.1.:36451 ::ffff:203.205.17:https SYN_SENT
tcp6       0      1 ::ffff:192.168.1.:46177 ::ffff:203.205.15:https SYN_SENT
tcp6       0      1 ::ffff:192.168.1.:34883 ::ffff:203.205.179:http SYN_SENT
tcp6       0      0 ::ffff:192.168.1.:40053 ::ffff:179.60.192:https ESTABLISHED
tcp6       1      0 ::ffff:192.168.1.:60669 ::ffff:172.217.18.:http CLOSE_WAIT
tcp6       0      0 ::ffff:192.168.1.:50722 ::ffff:216.58.210:https ESTABLISHED
hero2lte:/ $

**Comment by FxMath123** [comment]
and here run SSLSocks on port: 10002

hero2lte:/ $ netstat -at
Active Internet connections (established and servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:10002           0.0.0.0:*               LISTEN
tcp      417      0 Samsung-Galaxy-S7:33505 fra16s25-in-f10.1:https CLOSE_WAIT
tcp        1      0 Samsung-Galaxy-S7:58738 fra16s08-in-f204.1:http CLOSE_WAIT
tcp        1      0 Samsung-Galaxy-S7:42700 wq-in-f114.1e100.n:http CLOSE_WAIT
tcp        0      0 Samsung-Galaxy-S7:35201 ec2-35-177-52-76.:https TIME_WAIT
tcp        0      1 Samsung-Galaxy-S7:42347 149.154.167:xmpp-client SYN_SENT
tcp        0      1 Samsung-Galaxy-S7:34205 149.154.167.91:https    SYN_SENT
tcp        0      1 Samsung-Galaxy-S7:39836 149.154.167.92:https    SYN_SENT
tcp6       1      0 ::ffff:192.168.1.:60862 ::ffff:216.58.208:https CLOSE_WAIT
tcp6       0      0 ::ffff:192.168.1.:56594 ::ffff:74.125.71.1:5228 ESTABLISHED
tcp6       1      0 ::ffff:192.168.1.:37014 ::ffff:172.217.23:https CLOSE_WAIT
tcp6       1      0 ::ffff:192.168.1.:37016 ::ffff:172.217.23:https CLOSE_WAIT
tcp6       1      0 ::ffff:192.168.1.:60860 ::ffff:216.58.208:https CLOSE_WAIT
tcp6       1      0 ::ffff:192.168.1.:37015 ::ffff:172.217.23:https CLOSE_WAIT
tcp6       0      0 ::ffff:192.168.1.:40053 ::ffff:179.60.192:https ESTABLISHED
tcp6       0      0 ::ffff:192.168.1.:47857 ::ffff:172.217.18:https ESTABLISHED
tcp6       1      0 ::ffff:192.168.1.:39255 ::ffff:172.217.21:https CLOSE_WAIT
tcp6       0      0 ::ffff:192.168.1.:47865 ::ffff:172.217.18:https ESTABLISHED
tcp6       0      0 ::ffff:192.168.1.:39273 ::ffff:172.217.21:https ESTABLISHED
hero2lte:/ $


And shows "Address already in use(98)".

**Comment by comp500** [comment]
What is your full config file?

**Comment by FxMath123** [comment]
Client side:
foreground =yes
client=yes
pid=/data/user/link.infra.sslsocks/files/pid
[squid]
accept = 10002
connect =x.x.x.x:8888

Server side:
client = no
[squid]
accept = 8888
connect = 127.0.0.1:3128
cert = /etc/stunnel/stunnel.pem

I tried by SSH instead squid for port:443 server but same error.

I put stunnel.pem in certs/KEYS.

**Comment by comp500** [comment]
If it's showing up in netstat, that means that it is actually running. I'm not sure why it shows the error, if it does not appear in netstat when SSLSocks is running. Does it work regardless of the error?

**Comment by FxMath123** [comment]
Not, it doesn't work and changes my IP.
must change my IP to my external server IP and is this transfer all my mobile traffic through my stunnel to my server? right?
UDP & TCP?
And I will check more to find the problem and update here.
This is the first App I found use Stunnel, I'm using on my windows OS(Proxifier+Stunnel(squid)) and try to setup Android client.

**Comment by comp500** [comment]
No, SSLSocks doesn't have a VPN service (I originally planned to implement it but never did), it only tunnels single TCP connections through TLS.

It's basically just a wrapper for stunnel, so similarly to your Windows computer (where you need Proxifier) you'll need another app, like shadowsocks or ProxyDroid, to tunnel your phone's internet through stunnel and squid.
